data_path = '../data'
app_path = '../web-app'


naics_dict = {
    '11': 'Agriculture, Forestry, Fishing, and Hunting',
    '21': 'Mining, Quarrying, and Oil and Gas Extraction',
    '22': 'Utilities',
    '23': 'Construction',
    '31': 'Manufacturing',
    '32': 'Manufacturing',
    '33': 'Manufacturing',
    '42': 'Wholesale Trade',
    '44': 'Retail Trade',
    '45': 'Retail Trade',
    '48': 'Transportation and Warehousing',
    '49': 'Transportation and Warehousing',
    '51': 'Information',
    '52': 'Finance and Insurance',
    '53': 'Real Estate Rental and Leasing',
    '54': 'Professional, Scientific, and Technical Services',
    '55': 'Management of Companies and Enterprises',
    '56': 'Administrative and Support and Waste Management and Remediation Services',
    '61': 'Educational services',
    '62': 'Health Care and Social Assistance',
    '71': 'Arts, Entertainment, and Recreation',
    '72': 'Accommodation and Food Services',
    '81': 'Other Services (except Public Administration)',
    '92': 'Public Administration'
}

# Party affiliatoin of state governor, as of April 2019
# https://en.wikipedia.org/wiki/List_of_United_States_governors
gov_dict = {
    'AL': 'R',
    'AK': 'R',
    'AZ': 'R',
    'AR': 'R',
    'CA': 'D',
    'CO': 'D',
    'CT': 'D',
    'DE': 'D',
    'FL': 'R',
    'GA': 'R',
    'HI': 'D',
    'ID': 'R',
    'IL': 'D',
    'IN': 'R',
    'IA': 'R',
    'KS': 'D',
    'KY': 'R',
    'LA': 'D',
    'ME': 'D',
    'MD': 'R',
    'MA': 'R',
    'MI': 'D',
    'MN': 'D',
    'MS': 'R',
    'MO': 'R',
    'MT': 'D',
    'NB': 'R',
    'NV': 'D',
    'NH': 'R',
    'NJ': 'D',
    'NM': 'D', 
    'NY': 'D',
    'NC': 'D',
    'ND': 'R',
    'OH': 'R',
    'OK': 'R',
    'OR': 'D',
    'PA': 'D',
    'RI': 'D',
    'SC': 'R',
    'SD': 'R', 
    'TN': 'R',
    'TX': 'R',
    'UT': 'R',
    'VT': 'R',
    'VA': 'D', 
    'WA': 'D',
    'WV': 'R',
    'WI': 'D',
    'WY': 'R',
    'PR': 'NP',
}

#naics_dict = {
#    '11': 'Agriculture, Forestry, Fishing, and Hunting',
#    '2111': 'Oil and Gas Extraction',
#    '2121': 'Coal Mining',
#    '2122': 'Metal Ore Mining',
#    '2123': 'Nonmetallic Mineral Mining and Quarrying',
#    '2131': 'Support Activities for Mining',
#    '2211': 'Electric Power Generation, Transmission, and Distribution',
#    '2212': 'Natural Gas Distribution',
#    '2213': 'Water, Sewage, and Other Systems',
#    '23': 'Construction',
#    '31': 'Manufacturing',
#    '32': 'Manufacturing',
#    '33': 'Manufacturing',
#    '42': 'Wholesale Trade',
#    '44': 'Retail Trade',
#    '45': 'Retail Trade',
#    '48': 'Transportation and Warehousing',
#    '4862': 'Pipeline Transportation of Oil or Natural Gas',
#    '49': 'Transportation and Warehousing',
#    '51': 'Information',
#    '52': 'Finance and Insurance',
#    '53': 'Real Estate Rental and Leasing',
#    '54': 'Professional, Scientific, and Technical Services',
#    '55': 'Management of Companies and Enterprises',
#    '56': 'Administrative and Support and Waste Management and Remediation Services',
#    '61': 'Educational services',
#    '62': 'Health Care and Social Assistance',
#    '71': 'Arts, Entertainment, and Recreation',
#    '72': 'Accommodation and Food Services',
#    '81': 'Other Services (except Public Administration)',
#    '92': 'Public Administration'
#}